### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Zxilly** [You2php/delete#218]
`The media could not be loaded, either because the server or network failed or because the format is not supported.`
这个还修吗。。。是不是没人维护了

**Comment by t2015q** [comment]
我也是，大部分音乐视频都播放不了

**Comment by zxq2233** [comment]
是这样的，由于最近youtube接口算法加密方式改了，

导致无法解析出正确的下载地址。我目前已经在尝试修复了
具体请参见https://blog.maple3142.net/2018/05/05/how-to-download-youtube-video/

**Comment by FaArIsH** [comment]
@zxq2233
https://github.com/Athlon1600/youtube-downloader/pull/25

**Comment by zxq2233** [comment]
@t2015q @Zxilly 
替换YouTubeDownloader.php文件。把里面的代码换成这个

https://raw.githubusercontent.com/Athlon1600/youtube-downloader/bbb4349590a71938df7fe9277113e3da24c6c125/src/YouTubeDownloader.php

就可以了。

感谢
@FaArIsH  thank you!

**Comment by FaArIsH** [comment]
@zxq2233 its not working, i tried with the default file and now that too work with 360p videos

**Comment by arjunae** [comment]
.yo, just wanted to say thanks for your efforts with that like. 
Im not looking for hd content with my fork, so i just changed the regexp to cope with youtubes sep18 changes. 
But- for the current threads question - you might want to parse
'https://www.youtube.com/get_video_info?
and look for the [adaptive_fmts] array.

enjoy, arjunae

**Comment by ywjcpyw** [comment]
你好，我进行了代码的替换发现还是存在相同的问题。有部分视频存在此问题。
The media could not be loaded, either because the server or network failed or because the format is not supported.
我尝试多次刷新及浏览器的缓存清理，发现还是相同的问题
php版本7.2，使用的是宝塔+vultr的服务器

**Comment by joshatt** [comment]
> @t2015q @Zxilly
> 替换YouTubeDownloader.php文件。把里面的代码换成这个
> 
> https://raw.githubusercontent.com/Athlon1600/youtube-downloader/bbb4349590a71938df7fe9277113e3da24c6c125/src/YouTubeDownloader.php
> 
> 就可以了。
> 
> 感谢
> @FaArIsH thank you!

试了用这个文件替换, 视频列表中(也就是"相关内容"或"时下流行"), 第一行出现:
Notice: Undefined index: sortid in /home/xxxxx/ajax/ajax.php on line 17
然后列表中:
少数视频有预览图片, 大多数视频没有,替代以:"Undefined variable: lang in /home/xxxx/lib.php on line 128"
128这个数值, 列表中的每个视频不同, 不过都是在128~138

**Comment by Escher1108** [comment]
现在不行了呀。大佬。替换了都不能用。好桑心
