### ISSUE TITLE
有几个小建议

### ISSUE THREAD

**Issue by Aruelius** [You2php/delete#48]
1.比如音量调节，我觉得可以默认50%。
2.还有视频播放，可以点开之后就立刻播放，并且默认720p(如果考虑的是配置问题，那么这个可以放在config.php里面让用户自己调节)
3.视频播放还有一个问题，就是会循环播放，建议播放完一个视频停住，跟YouTube一样。
4.不显示标签，标签影响美观。
5.搜索联想功能。
6.有跟YouTube一样的剧场模式或者网页全屏，这样看起来挺方便的。
其他就非常棒了！

**Comment by zxq2233** [comment]
@MikuShare 收到！
